
Ttree:
  Plugin:
    LatexEditor:
      temporaryPath: '%FLOW_PATH_DATA%Temporary/LatexEditor/Rendering/'
      htlatexConfiguration: '%FLOW_PATH_PACKAGES%Plugins/Ttree.Plugin.LatexEditor/Resources/Private/Htlatex/ht5mjlatex.cfg'

TYPO3:

  Neos:

    typoScript:
      autoInclude:
        'Ttree.Plugin.LatexEditor': TRUE

    userInterface:

      requireJsPathMapping:
        'Ttree.Plugin.LatexEditor/Inspector/Editors': 'resource://Ttree.Plugin.LatexEditor/Public/JavaScript/Content/Inspector/Editors/'
        'Ttree.Plugin.LatexEditor/Library': 'resource://Ttree.Plugin.LatexEditor/Public/JavaScript/Library/'